# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-03 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190303_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
